--1
UPDATE LUCRARI_ARTA_PRJ
SET PRET_ESTIMATIV = PRET_ESTIMATIV * 1.10

WHERE AN_REALIZARE > 2020;
--2
UPDATE CLIENTI_PRJ
SET EMAIL = REPLACE(EMAIL, 'example.com', 'galerie.ro') WHERE EMAIL LIKE '%example.com';
--3
SELECT a.NUME, a.TARA_ORIGINE, COUNT(v.ID_VANZARE) AS NR_VANZARI, SUM(v.PRET_FINAL) AS TOTAL_INCASARI
FROM ARTISTI_PRJ a

JOIN LUCRARI_ARTA_PRJ l ON a.ID_ARTIST = l.ID_ARTIST JOIN VANZARI_PRJ v ON l.ID_LUCRARE = v.ID_LUCRARE GROUP BY a.NUME, a.TARA_ORIGINE
ORDER BY TOTAL_INCASARI DESC;

--4
SELECT c.NUME AS NUME_CLIENT, COUNT(v.ID_VANZARE) AS NR_TRANZACTII, SUM(v.PRET_FINAL) AS TOTAL_2022
FROM CLIENTI_PRJ c

JOIN VANZARI_PRJ v ON c.ID_CLIENT = v.ID_CLIENT WHERE EXTRACT(YEAR FROM v.DATA_VANZARE) = 2022 GROUP BY c.NUME
ORDER BY TOTAL_2022 DESC;
--5
SELECT e.NUME AS NUME_EXPOZITIE, e.LOCATIE, COUNT(DISTINCT l.ID_ARTIST) AS NR_ARTISTI_DISTINCTI
FROM EXPOZITII_PRJ e

JOIN LUCRARI_EXPOZITII_PRJ le ON e.ID_EXPOZITIE = le.ID_EXPOZITIE JOIN LUCRARI_ARTA_PRJ l ON le.ID_LUCRARE = l.ID_LUCRARE
GROUP BY e.NUME, e.LOCATIE

ORDER BY NR_ARTISTI_DISTINCTI DESC;
--6
SELECT a.ID_ARTIST,a.NUME FROM ARTISTI_PRJ a


WHERE (SELECT SUM(v.PRET_FINAL) FROM LUCRARI_ARTA_PRJ l
JOIN VANZARI_PRJ v ON l.ID_LUCRARE = v.ID_LUCRARE WHERE l.ID_ARTIST = a.ID_ARTIST
) >

(SELECT AVG(t.TOTAL_ARTIST) FROM (
SELECT l2.ID_ARTIST, SUM(v2.PRET_FINAL) AS TOTAL_ARTIST FROM LUCRARI_ARTA_PRJ l2
JOIN VANZARI_PRJ v2 ON l2.ID_LUCRARE = v2.ID_LUCRARE

GROUP BY l2.ID_ARTIST

) t);
--7
SELECT e.ID_EXPOZITIE, e.NUME, SUM(v.PRET_FINAL) AS TOTAL_EXPOZITIE FROM EXPOZITII_PRJ e
JOIN LUCRARI_EXPOZITII_PRJ le ON e.ID_EXPOZITIE = le.ID_EXPOZITIE JOIN LUCRARI_ARTA_PRJ l ON le.ID_LUCRARE = l.ID_LUCRARE
JOIN VANZARI_PRJ v ON l.ID_LUCRARE = v.ID_LUCRARE GROUP BY e.ID_EXPOZITIE, e.NUME
ORDER BY TOTAL_EXPOZITIE DESC;
--8
SELECT a.ID_ARTIST, a.NUME,
COUNT(DISTINCT le.ID_EXPOZITIE) AS NR_EXPOZITII

FROM ARTISTI_PRJ a

JOIN LUCRARI_ARTA_PRJ l

ON a.ID_ARTIST = l.ID_ARTIST JOIN LUCRARI_EXPOZITII_PRJ le
ON l.ID_LUCRARE = le.ID_LUCRARE GROUP BY a.ID_ARTIST, a.NUME
HAVING COUNT(DISTINCT le.ID_EXPOZITIE) >= 2

ORDER BY NR_EXPOZITII DESC;
